### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by medikoo** [gillesruppert/webmake-middleware#4]
@gillesruppert as I recently updated Webmake to support Node.js v10, I'd like to also publish updated version of this package (I use it in some small projects of mine).

Is there any chance you can publish it, or add me as a package owner, so I can publish it myself :)

I've already updated package with necessary changes

**Comment by gillesruppert** [comment]
@medikoo just added you as an admin to the package. Let me know if it doesn't work.

**Comment by medikoo** [comment]
Great thanks!
